---
title: SMP Process
categories: [reference, milk powder, commodity]
---

A general flow diagram for skim milk powder (SMP) is shown below:

```{mermaid}
%%| label: fig-SMP-embed
%%| fig-cap: "Skim Milk Powder flow diagram"
%%| file: ../Diagrams/SMP.mmd
```

Milk for processing into SMP has been skimmed and
pasteurised.

Pre-heating is required to attain the temperatures
necessary to evaporate water from the milk.

The severity (time $\times$ temperature) of pre-heating
also has a significant impact on functional properties
of the final powder.

::: {.callout-note}
## Heat Classification

The heat classification of a milk powder reflects
the severity of the pre-heating treatment applied.

Common classifications include: low-heat, medium-heat and high-heat.
Low-heat SMP has a low level of denatured whey protein, while high-heat
has a high level of denatured whey protein.

Denatured whey proteins interact interact with casein micelles in the
milk, which can increase stability to subsequent heating or renneting.

Milk powders of a specific classification are often selected depending
on the application.

For an example of how knowledge of heat classes can help
guide decision-making when supplying a customer read [this tutorial](../Tutorials/heatClassSupply.qmd).
:::

Evaporation to between 45-50% solids is typical during evaporation.
The evaporation is performed under a vacuum, permitting the removal
of water at low temperatures (60-70°C).
A common design of evaporator used is the falling-film evaporator.

Most milk powders are dried using spray-driers.
The concentrated milk generated by the evaporator
is pumped under high pressure through a nozzle.
The spray of concentrate that is generated
dries rapidly as it falls through a chamber
filled with dry, hot air.

While the temperature of the air at the inlet
can well exceed 100°C, the internal temperature
of the droplet rarely exceeds >70°C due to the
effect of evaporative cooling.

The drying step is usually designed to achieve
agglomeration, which improves the wetting behaviour
of the powder.
