---
title: WMP Process
categories: [reference, milk powder, commodity, fat]
---

The process for Whole Milk Powder (WMP) is similar to that described for
[SMP](./SMP_process.qmd) but with some important differences.

Most obviously, the starting material is whole
milk rather than skim milk.
The milk will have been standardised to a specific
fat content of around 3.5% and pasteurised.

Due to the significant presence of fat, milk for
WMP production must be treated as an unstable
emulsion.
Homogenisation is therefore applied to dispersed
the oil droplets into smaller sizes that float
more slowly.

::: {.callout-note}

It might not be obvious to you why a powder
would need a homogenisation step:

> If it's going to be dried anyway won't it be stable?

For one reason, please refer to [this short Concepts note](../Concepts/driedEmulsions.qmd).

:::

Evaporation proceeds as per SMP, with slightly
lower solids contents achievable due to the
increased viscosity imparted by the fat.

Most WMP is spray-dried and agglomerated.
Lecithination is also performed to ensure
the powder has "instant" properties.

```{mermaid}
%%| label: fig-WMP-embed
%%| fig-cap: "Whole Milk Powder flow diagram"
%%| file: ../Diagrams/WMP.mmd
```
