---
title: Types of Separation
categories: [concepts, separation]
---

It is common to hear the following five terms
when discussing ingredient development:

1. Separation
2. Concentration
3. Fractionation
4. Isolation
5. Enrichment

Sometimes these are used interchangeably, which
can lead to confusion.

Separation can be considered the most general
category of the five
The other four are each *types of separation*.
Any separation usually involves the processing
of a feed material such that at least two
outputs can be recovered.

Given a complex mixture, concentration usually
involves an increase in the concentration of
one or more components through the removal of
water.
Critically, this does not involve a change in
the relative proportion of the solid (non-water) 
components.

Fractionation usually refers to changes in
the relative proportions of solid components.
For example, given a binary feed A+B where
A is the component of interest, a process could
be designed to create two outputs, with one having a
proportion of A ($\frac{A}{A+B} \times 100$) that is 
increased relative to the starting feed.

The extent of fractionation usually determines
whether a process is called "isolation" or enrichment.
In the previous example, if the proportion of A
exceeds 90% it might be considered an isolation process.
On the other hand, if it was 60% (meaning the remaining
40% is B) then it would be considered an enrichment.

Another way to think about this is that isolation
usually has an absolute definition (a criteria of
purity for A) whereas enrichment usually has a relative
definition (an enrichment of A relative to B).
Isolation and purification are usually treated
as synonymous.


```{dot}
graph G {
  layout=neato;
  overlap=true;

  separation--concentration
  separation--drying
  separation--fractionation
  fractionation--enrichment
  fractionation--isolation

}
```

A last distinction is between concentration and drying.
Concentration usually refers to the removal of water to
increase the concentration of solids.
Evaporation and reverse osmosis are concentration processes.
Drying also involves the removal of water and the concentration
of solids; however, the decrease in water content is so
significant that it causes a physical transformation from
the liquid to the solid state.

::: {.callout-note}

Clearly it could also be said that in a fractionation
process the **concentration** of A changes relative to
B.

That is using "concentration" in the chemical sense,
whereas here we are are talking about it in the
sense of a manufacturing process.

:::

In summary, there is an unfortunately large number of technical
terms that are used to refer to similar processes.
Commonly we are dealing with some kind of separation,
although the separation can vary in extent.

It is important to keep these distinctions in mind when
dealing with complex multi-step processes.
For example, a feed might be microfiltrered (fractionation)
before being evporated (concentrated).
