flowchart LR

A[|borders:n|Skim Milk] --> B(Pre-heat)

B --> C(Acidification)

C --> D(Dewheying)

D --> E(Washing)

E --> F(Dewatering)

F --> G(Drying)

G --> H[|borders:n|ACN]

K[|borders:n|Acid] --> C(Acidification)

D --> J[|borders:n|Whey]
