flowchart LR

A[|borders:n|complex mixture] --> B(Dry) --> C[|borders:n|powder] 
D[|borders:n|skim milk] --> E(Dry) --> F[|borders:n|skim milk powder] 
G[|borders:n|liquid whey] --> H(Dry) --> I[|borders:n|whey powder] 
