flowchart LR
    input["Input
    - Lower value
    - High stability"]
    output["Output
    + Higher value
    + Higher stability"]
    coproduct["Coproduct
    ~ Potential value
    "]
    process["❓❓❓"]
    input --> process
    process --> output
    process --> coproduct
