flowchart LR

A[|borders:n|Whey permeate] --> B(Evaporate)

B --> C(Crystallisation)

C --> D(Centrifugation)

D --> E(Washing)

E --> F(Drying)

F --> G[|borders:n|Lactose]

D --> X[|borders:n|Delactosed whey]

Y[|borders:n|Water] --> E
