flowchart LR
A[|borders:n|Skim Milk] --> B(Incubate)
  B --> C(Dewhey)
  C --> D(Wash)
  D --> E(Dewater)
  E --> F(Dry)
F --> G[|borders:n|RCN]

H[|borders:n|Rennet] --> B(Incubate)

C --> J[|borders:n|Whey]
