flowchart TD
A[|borders:n|Acid casein powder] --> B(dilute)
  B --> C(Colloid mill)
  C --> D(Alkalise)
  D --> E(Mix)
  E --> F(High-shear)
  F --> G(Dry)
  G --> H[|borders:n|SCN]

I[|borders:n|Acid casein curd] --> J(mince)
  J --> K(Dilute)
  K --> L(Colloid mill)
  L --> M(Alkalise)
  M --> N(Mix)
  N --> O(High-shear)
  O --> P(Dry)
  P --> Q[|borders:n|SCN]


  X[|borders:n|NaOH] --> D
  Y[|borders:n|NaOH] --> M
