flowchart LR

A[|borders:n|Liquid whey] --> B(Microfiltration)

B --> C(Ultrafiltration)

C --> D(Evaporation)

D --> E(Drying)

E --> F[|borders:n|WPI]

B --> X[|borders:n|Whey phospholipids]

C --> Y[|borders:n|Whey permeate]

W[|borders:n|Water]--> C
